namespace Sekai
{
	public enum HonorMissionType
	{
		undefined = 0,
		easy_full_combo = 1,
		normal_full_combo = 2,
		hard_full_combo = 3,
		expert_full_combo = 4,
		clear_live = 5,
		player_rank = 6,
		login_continued = 7,
		login_total = 8,
		collect_another_vocal = 9,
		unit_rank_all = 10,
		area_item_5_level = 11,
		character_rank_all = 12,
		clear_live_difficulty_all = 13,
		master_full_combo = 14,
		master_full_perfect = 15,
		collect_coin_total = 16,
		clear_multi_live_full_combo_all = 17,
		multi_live_select_same_music = 18,
		multi_live_same_honor = 19,
		multi_live_stamp = 20,
		append_full_combo = 21,
		append_full_perfect = 22,
		duplicate_card_total = 23,
		collect_stamp = 24,
		action_set = 25,
		read_story_no_skip = 26,
		read_unit_story_no_skip = 27,
		clear_live_school_year_1 = 28,
		clear_live_school_year_2 = 29,
		clear_live_school_miyamasuzaka = 30,
		clear_live_school_kamiyama = 31,
		clear_live_male = 32,
		multi_live_mvp = 33,
		multi_live_super_star = 34,
		collect_costume_3d = 35,
		cheer_point_rank_1st = 36,
		cheer_point_rank_10th = 37,
		piapro_virtual_live_total_cheer_point = 38,
		theme_park_virtual_live_total_cheer_point = 39,
		idol_virtual_live_total_cheer_point = 40,
		clear_live_next_grade_school_year_2 = 41,
		clear_live_next_grade_school_year_3 = 42,
		street_virtual_live_total_cheer_point = 43,
		light_sound_virtual_live_total_cheer_point = 44,
		school_refusal_virtual_live_total_cheer_point = 45,
		send_friend_request = 46,
		make_friend = 47,
		clear_multi_live_all_friend = 48,
		play_level_clear = 49,
		play_level_full_combo_clear = 50
	}
}
